[package]
name = "file_encryption"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
aes-gcm = { version = "0.10.3", features = ["std"] }
dirs = "6.0.0"
hex = "0.4.3"
base64 = "0.22.1"
argon2 = "0.5.3"